production: 
  app: tweet-score
  stack: cedar
  config:
    BUNDLE_WITHOUT: "development:test"
  #  GOOGLE_ANALYTICS: "UA-12345678-1"
  addons:
    - pgbackups:auto-week
    - memcache:5mb
    - logging:basic
    - scheduler:standard